

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x240000e0,
     0xf1002081,
     0x240004e0,
     0xf1002082,
     0x240064e3,
     0x04e1e3e3,
     0x10e1e1e4,
     0x1f05fefe,
     0x10e2e2e0,
     0x0501e0e0,
     0x6f00e0ff,
     0x0501e4e4,
     0x6f00e4fc,
     0x10e3e3e4,
     0x1d05fefe,
     0x10e2e2e0,
     0x0501e0e0,
     0x6f00e0ff,
     0x0501e4e4,
     0x6f00e4fc,
     0xd103ff02,
     0x7f0000f1,
     0x2400231f,
     0x2a000000 };

