#!/bin/bash

echo "Compiling the overlay from .dts to .dtbo"

dtc -O dtb -o EBB-PRU-Example-00A0.dtbo -b 0 -@ EBB-PRU-Example.dts
cp EBB-PRU-Example-00A0.dtbo /lib/firmware/

dtc -O dtb -o BB-BONE-PRU1-00A0.dtbo -b 0 -@ BB-BONE-PRU1.dts
cp BB-BONE-PRU1-00A0.dtbo /lib/firmware/
